/* SIE CONFIDENTIAL
PlayStation(R)4 Programmer Tool Runtime Library Release 04.508.001
* Copyright (C) 2012 Sony Interactive Entertainment Inc.
* All Rights Reserved.
*/

void main(
	float2 aPosition : POSITION,
	out float4 oPosition : POSITION,

	uniform float2	offset,
	uniform float2	size,
	uniform float   depth
)
{
	float2 coord = offset + size * aPosition;
	float2 coord2 = coord * 2.0 - 1.0;

	oPosition.x = coord2.x;
	oPosition.y = - coord2.y;
	oPosition.z = depth;
	oPosition.w = 1.0f;
}


